version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: sketchpad
    volumes:
      - .:/opt/app
      # the node, build, and deps volumes are required due to excluding them
      # in the prod container via .dockerignore, unless you want to rebuild
      # deps and modules each time you start a container
      - build-data:/opt/app/_build
      - deps-data:/opt/app/deps
      - node-data:/opt/app/assets/node_modules
    ports:
      - "4000:4000"

volumes:
  build-data:
  deps-data:
  node-data:
